### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by chronofreak**
Pulled all icons from the skill tree planner on the official website.

### CODE REVIEW

**Comment by chronofreak** [comment]
@seigler The FL4K icons are already correct, so go ahead and merge these skill icons for the other three characters when you're ready!

**Comment by seigler** [comment]
Wow, this is great :grinning: 
It seems like the gunner icons are a little blurry -- is it like that on the official planner too?

**Comment by seigler** [comment]
(I'm going to merge this and the Gunner icons can be updated again later -- it's probably better to get the right-looking icons in even if they're a little blurry.

**Comment by seigler** [comment]
Nevermind, I dunno what was going on but the Gunner icons look sharp like the rest. Nice update :+1:

**Pull request merged**
